src/ideas/urls.py
from django.urls import path
from .views import idea_detail_view, ideas_and_request_ideas_view, contact_view, contact_view_ok, \
    IdeaCreateView, RequestIdeaCreateView, idea_create_confirm, request_idea_confirm, add_to_cart,\
    cart, delete_from_cart, create_checkout_session, checkout_success, stripe_webhook, my_ideas, about_us


app_name = "ideas"
urlpatterns = [
    path('all/', ideas_and_request_ideas_view, name="all"),
    path('idea/<str:slug>/', idea_detail_view, name="idea-detail"),
    path('cart/add-to-cart/<str:slug>/', add_to_cart, name="add-to-cart"),
    path('cart/', cart, name="cart"),
    path('cart/delete/<int:pk>/', delete_from_cart, name="delete-from-cart"),
    path('cart/create-checkout-session/', create_checkout_session, name="create-checkout-session"),
    path('cart/create-checkout-session/checkout-success/', checkout_success, name="checkout-success"),
    path('stripe-webhook/', stripe_webhook, name="stripe-webhook"),
    path('contact/', contact_view, name="contact"),
    path('contact/ok/', contact_view_ok, name="contact-ok"),
    path('create/idea/', IdeaCreateView.as_view(), name="create-idea"),
    path('create/request-idea/', RequestIdeaCreateView.as_view(), name="create-request-idea"),
    path('create/idea-confirm/', idea_create_confirm, name="create-idea-confirm"),
    path('create/request-idea-confirm/', request_idea_confirm, name="create-request-idea-confirm"),
    path('my-ideas/', my_ideas, name="my-ideas"),
    path('about/', about_us, name="about"),
]

src/remy/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings
from ideas.views import index

import os

from dotenv import load_dotenv

load_dotenv()

urlpatterns = [
    path(os.environ.get("ADMIN_URL"), admin.site.urls),
    path('', index, name="index"),
    path('account/', include('accounts.urls')),
    path('verification/', include('verify_email.urls')),
    path('ideas/', include('ideas.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_header = 'Invent for Tomorow'
admin.site.site_title = "Invent for Tomorow"

src/ideas/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.core.mail import send_mail
from django.utils import timezone
from accounts.models import Moderator
from remy.settings import AUTH_USER_MODEL
from ckeditor.fields import RichTextField


class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name="Nom")
    slug = models.SlugField(blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Catégorie"


class Idea(models.Model):
    name = models.CharField(max_length=200, verbose_name="Nom", unique=True)
    slug = models.SlugField(blank=True, unique=True)
    summary = models.CharField(max_length=1000, verbose_name="Résumé")
    level = models.CharField(choices=[(str(i), str(i)) for i in range(1, 4)],
                             help_text="1 : rapide, 2 : moyennement développé, 3 : très développé",
                             max_length=1,
                             verbose_name="Niveau",)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, verbose_name="Catégorie", null=True)
    thinker = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE,
                                verbose_name="Utilisateur", related_name="ideas")
    details = RichTextField()
    sketch = models.ImageField(upload_to="sketch_idea", blank=True, null=True, verbose_name="Croquis")
    date = models.DateField(auto_now_add=True)
    request = models.BooleanField(default=False, verbose_name="Demande d'idée",
                                  help_text="Cocher si c'est une demande d'idée,"
                                            " si c'est une idée (offre) ne pas cocher")
    status = models.BooleanField(default=False, verbose_name="Publié")
    price = models.FloatField(default=0, verbose_name="Prix")
    paid = models.BooleanField(default=False, verbose_name="Payé")
    buyer = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE,
                              verbose_name="Acheteur", null=True, related_name="purchases", blank=True)
    ordered_date = models.DateField(verbose_name="Date d'achat", null=True, blank=True)

    def email_to_admin_idea(self):
        moderators: Moderator = Moderator.objects.all()
        ideas = Idea.objects.all()

        if not self in ideas:
            email = send_mail(subject=f"{self.thinker} a soumis {self.name}",
                              message=f"{self.thinker} a soumis une idée :\n {self.details}",
                              from_email=None,
                              recipient_list=[moderator.email for moderator in moderators])
            return email

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        self.email_to_admin_idea()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('ideas:idea-detail', kwargs={"slug": self.slug})

    class Meta:
        verbose_name = "Idée / Demande d'idée"
        ordering = ["-date"]


class Comment(models.Model):
    content = RichTextField()
    idea = models.ForeignKey(Idea, on_delete=models.CASCADE, verbose_name="idée")
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="utilisateur")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} - {self.date} - {self.idea}"

    class Meta:
        verbose_name = "Commentaire"


class Cart(models.Model):
    buyer = models.OneToOneField(AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Acheteur")
    ideas = models.ManyToManyField(Idea, verbose_name="Idées")
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name="Date de création")

    def total_cart(self):
        total = 0
        for idea in self.ideas.all():
            total += idea.price

        return total

    def cart_paid(self, user):
        for idea in self.ideas.all():
            idea.paid = True
            idea.buyer = user
            idea.ordered_date = timezone.now()
            idea.save()

        # self.ideas.clear() non nécéssaire
        self.delete()

    class Meta:
        verbose_name = "Panier"

    def __str__(self):
        return f"Panier de {self.buyer} {self.creation_date}"

src/ideas/forms.py
from django import forms
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox
from .models import Comment


class ContactForm(forms.Form):
    email = forms.EmailField(label="Email")
    subject = forms.CharField(max_length=100, label="Objet", help_text="100 caractères max")
    message = forms.CharField(label="Message", max_length=5000, help_text="5000 caractères max", widget=forms.Textarea)
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)


class IdeaCommentForm(forms.ModelForm):
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)

    class Meta:
        model = Comment
        fields = ["content"]

src/ideas/views.py
import os
import stripe

from django.core.paginator import Paginator
from django.forms import model_to_dict
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.generic import CreateView

from accounts.models import ShippingAddresse, Thinker
from .models import Idea, Comment, Cart
from .forms import ContactForm, IdeaCommentForm
from remy.settings import STRIPE_KEY

# On branch test
stripe.api_key = STRIPE_KEY


def index(request):
    context = {}

    count_ideas = Idea.objects.filter(status=True, paid=False, request=False).count()
    if count_ideas >= 4:
        context["ideas"]: Idea = Idea.objects.filter(status=True,
                                                     paid=False, request=False)[count_ideas - 4:count_ideas]
    else:
        context["ideas"]: Idea = Idea.objects.filter(status=True, paid=False, request=False)

    count_request_ideas = Idea.objects.filter(status=True, request=True, paid=False).count()
    if count_request_ideas >= 4:
        context["request_ideas"]: Idea = \
            Idea.objects.filter(status=True,
                                request=True, paid=False)[count_request_ideas - 4:count_request_ideas]
    else:
        context["request_ideas"]: Idea = Idea.objects.filter(status=True, request=True, paid=False)

    return render(request, template_name="ideas/index.html", context=context)


@login_required()
def idea_detail_view(request, slug):
    user = request.user
    idea = get_object_or_404(Idea, slug=slug)
    if idea.paid:
        # Si l'idée est payée
        if user != idea.thinker and user != idea.buyer:
            # Si l'utilisateur est différent de l'auteur ou si l'utilisateur est différent de l'acheteur
            # Si je suis auteur : False and True = False
            # Si je suis acheteur : True and False = False
            # Si je ne suis ni l'un ni l'autre : True and True = True
            return HttpResponse(status=410)

    comments = Comment.objects.filter(idea=idea).order_by('date')

    if request.method == "POST":
        form = IdeaCommentForm(request.POST)
        if form.is_valid():
            form.instance.user = user
            form.instance.idea = idea
            form.save()
            return redirect(idea)
    else:
        form = IdeaCommentForm()

    return render(request, "ideas/idea.html", context={"idea": idea, "form": form,
                                                       "comments": comments})


def add_to_cart(request, slug):
    # user = request.user
    #
    # user_cart, _ = Cart.objects.get_or_create(buyer=user)
    # idea = get_object_or_404(Idea, slug=slug)
    #
    # if request.method == "POST":
    #
    #     if idea in user_cart.ideas.all():
    #         # On ne peut pas ajouter deux fois la même idée
    #         messages.add_message(request, messages.ERROR, "L'idée est déjà dans le panier")
    #         return redirect("ideas:all")
    #
    #     for cart in Cart.objects.all():
    #         # Je vérifie que l'idée ne soit pas dans le panier d'un autre
    #         if idea in cart.ideas.all():
    #             messages.add_message(request, messages.ERROR, "L'idée est déjà dans le panier de quelqu'un.")
    #     else:
    #         user_cart.ideas.add(idea)
    #         # On ajoute au panier et on va dans la vue panier
    #
    #         return redirect("ideas:cart")

    user = request.user
    user_cart, _ = Cart.objects.get_or_create(buyer=user)
    idea = get_object_or_404(Idea, slug=slug)

    if request.method != "POST":
        raise Http404("Requête invalide")

    if user_cart.ideas.filter(id=idea.id).exists() or Cart.objects.filter(ideas__id=idea.id).exists():
        # si l'idée existe dans le panier ou si un panier avec l'idée existe
        messages.add_message(request, messages.ERROR, "L'idée est déjà dans le panier")
        return redirect("ideas:all")
    else:
        user_cart.ideas.add(idea)  # Ajoute l'idée au panier de l'utilisateur
        return redirect("ideas:cart")


@login_required()
def cart(request):
    context = {}
    user = request.user

    context["cart"] = user.cart

    return render(request, "ideas/cart.html", context=context)


def delete_from_cart(request, pk):
    user = request.user
    cart = user.cart
    idea = cart.ideas.get(pk=pk)

    if request.method == "POST":
        cart.ideas.remove(idea)
        if not cart.ideas.all():
            cart.delete()
            # voir pour utiliser messages "Plus rien dans le panier"
            return redirect("index")
    return redirect("ideas:cart")


def create_checkout_session(request):
    cart = request.user.cart

    checkout_data = {
        "locale": "fr",
        "line_items": [{
            'price_data': {
                'currency': 'eur',
                'product_data': {
                    'name': idea.name,
                },
                'unit_amount': int(idea.price * 100),
            },
            'quantity': 1,
        } for idea in cart.ideas.all()],
        "automatic_tax": {'enabled': True},
        "mode": 'payment',
        "invoice_creation": {"enabled": True},
        "shipping_address_collection": {"allowed_countries": ["FR", "BE"]},
        "success_url": request.build_absolute_uri(reverse("ideas:checkout-success")),
        "cancel_url": 'http://127.0.0.1:8000'}

    if request.user.stripe_id:
        checkout_data["customer"] = request.user.stripe_id
        checkout_data["customer_update"] = {"shipping": "auto"}
    else:
        checkout_data["customer_email"] = request.user.email
        checkout_data["customer_creation"] = "always"

    session = stripe.checkout.Session.create(**checkout_data)

    return redirect(session.url, code=303)


def checkout_success(request):
    return render(request, 'ideas/success-payment.html')


@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    # Penser à renseigner une clé pour la prod
    endpoint_secret = os.environ.get('endpoint_secret')
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, endpoint_secret
        )
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)

    # Handle the event
    if event.type == 'checkout.session.completed':
        data = event['data']['object']

        user = get_object_or_404(Thinker, email=data['customer_details']['email'])
        cart = user.cart

        if not user.stripe_id:
            user.stripe_id = data["customer"]
            user.save()

        ShippingAddresse.objects.get_or_create(
            thinker=user,
            name=data["shipping_details"]["name"],
            city=data["shipping_details"]["address"]["city"],
            country=data["shipping_details"]["address"]["country"],
            line1=data["shipping_details"]["address"]["line1"],
            line2=data["shipping_details"]["address"]["line2"] or "",
            zip_code=data["shipping_details"]["address"]["postal_code"],
        )

        cart.cart_paid(user=user)

    return HttpResponse(status=200)


def ideas_and_request_ideas_view(request):
    ideas = Idea.objects.filter(status=True, paid=False, request=False)
    request_ideas = Idea.objects.filter(status=True, paid=False, request=True)

    search = request.GET.get("search")
    if search:
        ideas = Idea.objects.filter(name__icontains=search, status=True, paid=False, request=False)
        request_ideas = Idea.objects.filter(name__icontains=search, status=True, paid=False, request=True)

    # paginator = Paginator(ideas | request_ideas, 2)
    # page_number = request.GET.get("page")
    # page_obj = paginator.get_page(page_number)

    return render(request, "ideas/all.html", context={'ideas': ideas,
                                                      'request_ideas': request_ideas})


class IdeaCreateView(LoginRequiredMixin, CreateView):
    model = Idea
    template_name = "ideas/create-idea.html"
    fields = ["name", "summary", "level", "category", "details", "sketch"]
    success_url = reverse_lazy('ideas:create-idea-confirm')

    def form_valid(self, form):
        form.instance.thinker = self.request.user
        return super().form_valid(form)


def idea_create_confirm(request):
    return render(request, "ideas/create-idea-confirm.html")


class RequestIdeaCreateView(LoginRequiredMixin, CreateView):
    model = Idea
    fields = ["name", "summary", "level", "category", "details", "sketch"]
    template_name = "ideas/create-request-idea.html"
    success_url = reverse_lazy('ideas:create-request-idea-confirm')

    def form_valid(self, form):
        form.instance.thinker = self.request.user
        form.instance.request = True
        return super().form_valid(form)


def request_idea_confirm(request):
    return render(request, "ideas/create-request-idea-confirm.html")


def contact_view(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            subject = form.cleaned_data["subject"]
            message = form.cleaned_data["message"]
            send_mail(subject=subject,
                      message=f"Message de {email} \n{message}",
                      from_email=None,
                      recipient_list=["remysevestre@yahoo.com"])
            # recipient_list : penser à passer une liste !
            # from_email None (va chercher dans les settings)

src/ideas/templates/ideas/about.html
{% extends 'base.html' %}

{% block head %}
<title>A propos</title>

{% endblock %}


{% block body %}

<div class="container" style="margin-top: 50px;">
	<div class="row">
	<div class="col-xxl-5 col-xl-5 col-lg-12" style="background-color: GhostWhite; padding: 30px; border-radius: 30px; margin-bottom: 30px;">

		<h4>Pourquoi devenir offreur d'idées ?</h4>

		<ul>
			<li>Notre site permet à chacun de se rémunérer grâce aux idées découlant de ses expériences, passions, connaissances.. . Les idées sont infinies c'est pourquoi il est naturel de pouvoir se rémunérer grâce à elles.</li>
			<li>Il offre également la possibilité d'accéder aux demandes, problématiques des entreprises ou autres organismes permettant une double possibilité de rémunération.</li>
			<li>L'inscription, les offres d'idées, la vérification et la protection sont disponibles gratuitement, donc aucun frais ne sera demandé aux offreurs d'idées.</li>
			<li>Ces offres d'idées sont accessibles à tous suivant le temps disponible et les besoins de chacun grâce à 3 niveaux : idée peu développée, moyennement développée et très développée.</li>
			<li>Les offres d'idées peuvent être réalisées dans n'importe quel domaine d'activité.</li>
			<li>Les offreurs pourront discuter entre eux via notre messagerie pour bénéficier d'informations, réaliser leurs expériences, co-créer.. mais aussi pour discuter avec les demandeurs d'idées.</li>
			<li>Notre site permet d'accéder à des outils gratuits pour faciliter au maximum le développement de son idée.</li>
			<li>Les offreurs pourront donc soit se rémunérer en proposant leurs propres idées ou bien en répondant aux problématiques des entreprises.</li>
			<li>Les offreurs prendront en compte l'impact environnemental de leurs idées, de ce fait ils contribueront à des innovations, inventions, decouvertes plus justes tout en luttant contre l'appauvrissement des ressources et le réchauffement climatique.</li>
			<li>Plus le nombre de demandeurs d'idées (entreprises, organismes publics, privés) sera élevé plus les idées des offreurs seront susceptibles d'êtres achetées et plus ils auront accès à des demandes diverses.</li>
			<li>Enfin ils se verront attribuer à chaque contribution d'une offre d'idée, une graine d'arbre qui sera planté en leur nom.</li>
		</ul>
	</div>
		<div class="col col-1"></div>
	<div class="col-xxl-5 col-xl-5 col-lg-12" style="background-color: LavenderBlush; padding: 30px; border-radius: 30px; margin-bottom: 30px;">

		<h4>Pourquoi devenir demandeur d'idées ?</h4>

		<ul>
			<li>
				Notre site offre la possibilité de proposer des problématiques auxquelles font face les entreprises mais aussi de pouvoir doublement trouver des solutions :
				<ul>
					<li>Soit par la réponse des offreurs d'idées à leur demande </li>
					<li>soit en recherchant des idées inédites dans la bibliothèque d'idées.</li>
				</ul>
			</li>
			<li>Notre site offre la possibilité de diminuer les coûts des entreprises et d'augmenter leurs productivité et compétitivité enaccédant à une multitude d'idées riches et variées puisque résultant de ressources et compétences diverses. (notamment des idées auxquelles ils n'auraient pas pensé en interne ou dont ils n'ont pas les compétences.)</li>
			<li> Il offre également la possibilité d'externaliser une partie, ou l'intégralité de leurs recherche grâce à cette multitude d'idées et notamment grâce aux 3 niveaux : Idées peu développée, moyennement développée et très développée.</li>
			<li>Il permet de choisir des idées plus ou moins développées donc plus ou moins chères suivant leurs besoins.</li>
			<li>Il offre la possibilité d'échanger via notre messagerie avec les offreurs pour par exemple avoir plus de détails sur leurs idées, co-créer avec eux..</li>
			<li>Notre site permet de bénéficier d'outils facilitant l'accès aux idées, notamment en recherchant par mot clé des idées dont ils auraient besoin.</li>
			<li>Les idées offertes permettront d'intégrer de manière plus ou moins développées leurs impacts environnementaux, permettant de répondre aux contraintes réglementaires mais aussi d'innover durablement.</li>
			<li>Les demandeurs d'idées se verront attribué une graine d'arbre en leurs noms pour chaque demande réalisée tout comme les offreurs d'idées.</li>
		</ul>
	</div>
		</div>
	<div class="row" style="margin-top: 50px; background-color: FloralWhite; margin-bottom: 15px; border-radius: 30px; padding: 15px;">
		<h4>Qui sommes nous ?</h4>

		<p>
			Je m'appelle Rémy, j'ai 26 ans et j'ai effectué une licence à l'université d'Évry puis un Master finance à l'INSEEC Business School à Paris. Je suis depuis peu de temps dans la vie active au poste de contrôleur de gestion.
		</p>
		<p>
			J'ai depuis toujours réalisé des petits projets surtout artistiques et lu beaucoup de livres en m'intéressant de près à l'innovation et l'environnement. Il s'avère que ces 2 thématiques sont passionnantes car elles sont à la fois opposées et se rejoignent. En effet l'innovation entraîne une hausse de l'épuisement des ressources et des émissions à cause de son effet volume mais peut être à la source de grands changements comme avec les énergies renouvelables.
		</p>
		<p>
			C'est donc ce que j'essaie de combiner au sein de cette entreprise où l'objectif est d'innover durablement. De plus mon autre but est que tout le monde puisse devenir acteur de ce changement puisque les ressources et compétences sont inégalement réparties et que les idées peuvent surgir de partout.
		</p>

		</div>
</div>

{% endblock %}

src/ideas/templates/ideas/all.html
{% extends 'base.html' %}

{% block head %}
<title>Toutes les idées</title>

{% endblock %}


{% block body %}
<div class="container">
	<form class="d-flex" role="search">
		<input class="form-control me-2" type="search" placeholder="Rechercher" aria-label="Search" name="search">
		<button class="btn btn-dark" type="submit">Rechercher</button>
	</form>
</div>

<div class="container" style="margin-bottom: 15px;">
{% if messages %}
{% for message in messages %}
	<h5 style="color: Red;">{{ message }}</h5>
{% endfor %}
{% endif %}
</div>

<div class="container" style="margin-bottom: 15px;">
	<div class="row">
		<div class="col-6">
			<h4>Idées publiées</h4>
			{% for idea in ideas %}
			<div class="card">
				<div class="card-header">
					Le {{ idea.date }} par {{ idea.thinker.username }}
				</div>
				<div class="card-body">
					<h5 class="card-title">
						{{ idea.name }}
					</h5>
					<p class="card-text">
						{{ idea.summary }}
					</p>
					<a href="{% url 'ideas:idea-detail' slug=idea.slug %}" class="btn btn-primary">Voir le détail</a>
				</div>
			</div>
			{% endfor %}
		</div>
		<div class="col-6">
			<h4>Demandes d'Idées publiées</h4>
			{% for request_idea in request_ideas %}
			<div class="card">
				<div class="card-header">
					Le {{ request_idea.date }} par {{ request_idea.thinker.username }}
				</div>
				<div class="card-body">
					<h5 class="card-title">
						{{ request_idea.name }}
					</h5>
					<p class="card-text">
						{{ request_idea.summary }}
					</p>
					<a href="{% url 'ideas:idea-detail' slug=request_idea.slug %}" class="btn btn-primary">Voir le détail</a>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
<!--
	<div class="row">
	<span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
	</div>
-->

</div>

{% endblock %}

src/ideas/templates/ideas/cart.html
{% extends 'base.html' %}

{% block head %}
<title>Panier</title>

{% endblock %}


{% block body %}



<div class="container">
<div class="row">
    <p>Votre panier <b>{{ cart.buyer.username }}</b></p>
</div>
    {% for idea in cart.ideas.all %}
  <div class="row">

<div class="card" style="width: 18rem;">

    <ul class="list-group list-group-flush">

    <li class="list-group-item">Idée "{{ idea.name }}" <br>de {{ idea.thinker }}<br>{{ idea.price }} €</li>
  </ul>

    <form method="post" action="{% url 'ideas:delete-from-cart' pk=idea.pk %}">
        {% csrf_token %}
        <input type="submit" value="Supprimer" class="btn btn-danger" style="margin-bottom: 10px;">
    </form>

</div>
  </div>

    {% endfor %}
<div class="row">

    <b>Total du panier : {{ cart.total_cart }}</b>
<div class="row">
<form action="{% url 'ideas:create-checkout-session' %}" method="post">
    {% csrf_token %}
<button type="submit">Procéder au paiement</button>

</form>

</div>
</div>
</div>

{% endblock %}

src/ideas/templates/ideas/contact-ok.html
{% extends 'base.html' %}

{% block head %}
<title>Message bien envoyé</title>

{% endblock %}


{% block body %}
<div class="container" style="margin-top: 100px;">
    <h3>L'email a bien été envoyé. Nous vous répondrons dans les 48H. Merci</h3>

</div>
{% endblock %}

src/ideas/templates/ideas/idea.html
{% extends 'base.html' %}

{% block head %}
<title>{{ idea.name }}</title>

{% endblock %}


{% block body %}
{% if not idea.paid and idea.status %}
{% if request.user.is_authenticated %}
<div class="container text-center buy">
	<form method="post" action="{% url 'ideas:add-to-cart' slug=idea.slug %}">
		{% csrf_token %}
<input type="submit" value="Acheter l'idée">
	</form>
	<h4>Prix : {{ idea.price }} €</h4>
</div>
{% endif %}
{% endif %}

<div class="container text-center idea">
	<div class="row">
		<h1>{{ idea.name }}</h1>
		<div class="detail">
			{{ idea.details|safe }}
		</div>
	</div>
	<div class="row">

		{% if idea.sketch %}
			<p>Croquis :</p>
		<a href="{{ idea.sketch.url }}" target="_blank"><img src="{{ idea.sketch.url }}" class="rounded mx-auto d-block" alt="croquis de {{ idea.name }}" width="200"></a>
		{% endif %}

	</div>
	<div class="row">
		<div class="published">
			<i>Publié par {{ idea.thinker.username }} le {{ idea.date }}</i><br>

		</div>
	</div>
</div>

{% if idea.status %}
<div class="container text-center" style="margin-top:20px;">
	<h3>Commentaires</h3>
	{% for comment in comments %}
<div class="card">
  <div class="card-header">
	  {{ comment.user.username }} - {{ comment.date }}
  </div>
  <div class="card-body">

    <p class="card-text">{{ comment.content|safe }}</p>

  </div>
</div>
{% endfor %}
</div>



<div class="container text-center" style="margin-top: 50px;">
	<div class="row justify-content-center">
<div class="col">
<form method="post">
    {% csrf_token %}
	{{ form.media }}
    {{ form.as_p }}
    <input type="submit" value="Envoyer" class="btn btn-success">
</form>
</div>
	</div>



</div>
{% endif %}
{% endblock %}

src/ideas/templates/ideas/success-payment.html
{% extends 'base.html' %}

{% block head %}
<title>Paiement réussi</title>

{% endblock %}


{% block body %}
<div class="container text-center">

    <h3>Votre paiement a été accepté</h3>

</div>

{% endblock %}