src/accounts/urls.py
from django.urls import path
from .views import signup, activate_account, login_thinker, logout_thinker, profil_thinker, \
    ThinkerPasswordChange, ThinkerPasswordReset, ThinkerPasswordResetDone, ThinkerPasswordResetConfirm, \
    ThinkerPasswordResetComplete, change_thinker_email

app_name = "account"
urlpatterns = [
    path('signup/', signup, name="signup"),
    path('go-to-mailbox/', activate_account, name="go-to-mailbox"),
    path('login/', login_thinker, name='login'),
    path('logout/', logout_thinker, name="logout"),
    path('profile/', profil_thinker, name="profile"),
    path('change-email', change_thinker_email, name="change-email"),
    path('new-password/', ThinkerPasswordChange.as_view(), name="change-password"),
    path('reset-password/', ThinkerPasswordReset.as_view(), name="reset-password"),
    path('reset-done/', ThinkerPasswordResetDone.as_view(), name="reset-done"),
    path('reset-confirm/<str:uidb64>/<str:token>/', ThinkerPasswordResetConfirm.as_view(), name="reset-confirm"),
    path('reset-complete/', ThinkerPasswordResetComplete.as_view(), name="reset-complete")
]

src/ideas/urls.py
from django.urls import path
from .views import idea_detail_view, ideas_and_request_ideas_view, contact_view, contact_view_ok, \
    IdeaCreateView, RequestIdeaCreateView, idea_create_confirm, request_idea_confirm, add_to_cart,\
    cart, delete_from_cart, create_checkout_session, checkout_success, stripe_webhook, my_ideas, about_us


app_name = "ideas"
urlpatterns = [
    path('all/', ideas_and_request_ideas_view, name="all"),
    path('idea/<str:slug>/', idea_detail_view, name="idea-detail"),
    path('cart/add-to-cart/<str:slug>/', add_to_cart, name="add-to-cart"),
    path('cart/', cart, name="cart"),
    path('cart/delete/<int:pk>/', delete_from_cart, name="delete-from-cart"),
    path('cart/create-checkout-session/', create_checkout_session, name="create-checkout-session"),
    path('cart/create-checkout-session/checkout-success/', checkout_success, name="checkout-success"),
    path('stripe-webhook/', stripe_webhook, name="stripe-webhook"),
    path('contact/', contact_view, name="contact"),
    path('contact/ok/', contact_view_ok, name="contact-ok"),
    path('create/idea/', IdeaCreateView.as_view(), name="create-idea"),
    path('create/request-idea/', RequestIdeaCreateView.as_view(), name="create-request-idea"),
    path('create/idea-confirm/', idea_create_confirm, name="create-idea-confirm"),
    path('create/request-idea-confirm/', request_idea_confirm, name="create-request-idea-confirm"),
    path('my-ideas/', my_ideas, name="my-ideas"),
    path('about/', about_us, name="about"),
]

src/remy/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings
from ideas.views import index

import os

from dotenv import load_dotenv

load_dotenv()

urlpatterns = [
    path(os.environ.get("ADMIN_URL"), admin.site.urls),
    path('', index, name="index"),
    path('account/', include('accounts.urls')),
    path('verification/', include('verify_email.urls')),
    path('ideas/', include('ideas.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_header = 'Invent for Tomorow'
admin.site.site_title = "Invent for Tomorow"

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

{% block head %}
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<header>
  <div class="container-fluid">
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Accueil</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">

          {% if not request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'account:signup' %}">Inscription</a>
        </li>
         <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'account:login' %}">Connexion</a>
        </li>
          {% else %}
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'account:logout' %}">Déconnexion</a>
        </li>
        {% if request.user.cart %}
         <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'ideas:cart' %}">Panier</a>
        </li>
        {% endif %}
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'account:profile' %}">Mon profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'ideas:my-ideas' %}">Mes idées/demandes</a>
        </li>
          {% endif %}
            <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'ideas:contact' %}">Nous contacter</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'ideas:about' %}">A propos</a>
        </li>
        {% if request.user.is_staff %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Administration de l'application</a>
        </li>
        {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Explorer
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'ideas:all' %}">Idées / Demandes d'idées</a></li>
            <li><a class="dropdown-item" href="{% url 'ideas:create-idea' %}">Déposer une idée</a></li>
            <li><a class="dropdown-item" href="{% url 'ideas:create-request-idea' %}">Déposer une recherche d'idée</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
  </div>
</header>


<body>
{% block body %}
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>

</html>