src/accounts/urls.py
from django.urls import path
from .views import signup, activate_account, login_thinker, logout_thinker, profil_thinker, \
    ThinkerPasswordChange, ThinkerPasswordReset, ThinkerPasswordResetDone, ThinkerPasswordResetConfirm, \
    ThinkerPasswordResetComplete, change_thinker_email

app_name = "account"
urlpatterns = [
    path('signup/', signup, name="signup"),
    path('go-to-mailbox/', activate_account, name="go-to-mailbox"),
    path('login/', login_thinker, name='login'),
    path('logout/', logout_thinker, name="logout"),
    path('profile/', profil_thinker, name="profile"),
    path('change-email', change_thinker_email, name="change-email"),
    path('new-password/', ThinkerPasswordChange.as_view(), name="change-password"),
    path('reset-password/', ThinkerPasswordReset.as_view(), name="reset-password"),
    path('reset-done/', ThinkerPasswordResetDone.as_view(), name="reset-done"),
    path('reset-confirm/<str:uidb64>/<str:token>/', ThinkerPasswordResetConfirm.as_view(), name="reset-confirm"),
    path('reset-complete/', ThinkerPasswordResetComplete.as_view(), name="reset-complete")
]

src/remy/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings
from ideas.views import index

import os

from dotenv import load_dotenv

load_dotenv()

urlpatterns = [
    path(os.environ.get("ADMIN_URL"), admin.site.urls),
    path('', index, name="index"),
    path('account/', include('accounts.urls')),
    path('verification/', include('verify_email.urls')),
    path('ideas/', include('ideas.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_header = 'Invent for Tomorow'
admin.site.site_title = "Invent for Tomorow"

src/accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from remy.settings import AUTH_USER_MODEL
import countryphonelist


class ThinkerManager(BaseUserManager):
    def create_user(self, email, username, phone, first_name, last_name, password, country, **kwargs):
        if not email:
            raise ValueError("Merci de renseigner un email svp")
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, phone=phone, first_name=first_name, last_name=last_name,
                          country=country,
                          **kwargs)
        user.set_password(password)
        user.is_active = False
        user.format_phone_number()
        user.save()
        return user

    def create_superuser(self, email, username, phone, first_name, last_name, password, country, **kwargs):
        user = self.create_user(email=email, username=username, phone=phone, first_name=first_name, last_name=last_name,
                                password=password, country=country, **kwargs)
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.save()
        return user


class Thinker(AbstractUser):
    phone = models.CharField(max_length=25, verbose_name="Téléphone")
    email = models.EmailField(unique=True, max_length=100)
    company = models.CharField(max_length=500, blank=True, verbose_name="Entreprise")
    country = models.CharField(max_length=100, choices=countryphonelist.COUNTRY, verbose_name="Pays")
    stripe_id = models.CharField(max_length=500, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username", "phone", 'first_name', 'last_name', 'country']

    objects = ThinkerManager()

    def format_phone_number(self):
        if not self.phone.startswith('+'):
            phone_number = self.phone.lstrip('0')
            for i in countryphonelist.DIAL:
                if i[0] == self.country:
                    dial_code = i[1]
                    phone_number = dial_code + phone_number
                    self.phone = phone_number

                    return self.phone
        return self.phone


class Moderator(models.Model):
    email = models.EmailField(max_length=100)
    pseudo = models.CharField(max_length=100)

    def __str__(self):
        return self.pseudo

    class Meta:
        verbose_name = "Modérateur"


class ShippingAddresse(models.Model):
    thinker = models.ForeignKey(AUTH_USER_MODEL, models.CASCADE, related_name="addresses")
    name = models.CharField(max_length=100, verbose_name="Nom de l'adresse")
    line1 = models.CharField(max_length=500, verbose_name="Adresse")
    line2 = models.CharField(max_length=200, verbose_name="Adresse / Complément",
                             help_text="Num d'appt etc...", default="")
    zip_code = models.CharField(max_length=10, verbose_name="Code postal")
    city = models.CharField(max_length=100, verbose_name="Ville")
    country = models.CharField(max_length=100, verbose_name="Pays")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Adresse"

src/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms


class ThinkerCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ["email", "username", "first_name", "last_name", "phone", "company", "country"]


class ThinkerProfilForm(forms.ModelForm):
    # disabled True va griser le champ. On verra les infos affichées mais rien ne sera envoyé
    email = forms.EmailField(help_text="L'email ne peut pas être modifié ici")
    password = forms.CharField(widget=forms.PasswordInput(), label="Mot de passe")
    first_name = forms.CharField(disabled=True, max_length=100, label="Prénom")
    last_name = forms.CharField(disabled=True, max_length=100, label="Nom")
    username = forms.CharField(disabled=True, max_length=100, label="Pseudo")

    class Meta:
        model = get_user_model()
        fields = ["email", "username", "password", "first_name",
                  "last_name", "phone", "company", "country"]


class ThinkerEmailForm(forms.Form):
    email = forms.EmailField(label="Email actuel")
    new_email = forms.EmailField(label="Nouvel Email")
    password = forms.CharField(widget=forms.PasswordInput(), label="Mot de passe")

src/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.forms import model_to_dict
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from verify_email.email_handler import send_verification_email
from .forms import ThinkerCreationForm, ThinkerProfilForm, ThinkerEmailForm
from .models import Thinker


def signup(request):

    if request.method == "POST":
        form = ThinkerCreationForm(request.POST)
        # S'il n'est pas valide je vais au return avec les données
        if form.is_valid():
            # form.save()
            inactive_user = send_verification_email(request, form)
            return redirect('account:go-to-mailbox')
    # Si get
    else:
    # si j'enlève le else et que je mets le form à ce niveau, en cas de post non valid j'ai un formulaire vide
        form = ThinkerCreationForm()

    return render(request, 'accounts/signup.html', context={"form": form})


def activate_account(request):
    # verify email
    return render(request, "accounts/signup-valid.html")


def login_thinker(request):
    context = {}
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        user = authenticate(email=email, password=password)
        if user:
            login(request, user)
            return redirect('index')
        else:
            context["error"] = "Email et/ou mot de passe non valide."

    return render(request, 'accounts/login.html', context=context)


def logout_thinker(request):
    logout(request)
    return redirect('index')


@login_required()
def profil_thinker(request):
    context = {}
    if request.method == "POST":
        user_auth = authenticate(email=request.POST.get("email"), password=request.POST.get("password"))
        # Si pas auth je vais charger le formulaire avant le return puis return en prenant l'erreur au passage
        if user_auth:
            user: Thinker = request.user
            user.phone = request.POST.get('phone')
            user.company = request.POST.get('company')
            user.country = request.POST.get('country')
            user.format_phone_number()
            user.save()
            return redirect('account:profile')
        else:
            # https://docs.djangoproject.com/en/4.2/ref/contrib/messages/#using-messages-in-views-and-templates
            # messages.add_message(request, messages.ERROR, "Le mot de passe n'est pas valide")
            context['error'] = "Mot de passe invalide"

    # model_to_dict(instance)
    context['form'] = ThinkerProfilForm(initial=model_to_dict(request.user, exclude='password'))

    return render(request, "accounts/profil.html", context=context)


@login_required()
def change_thinker_email(request):
    user = request.user
    all_users = Thinker.objects.all()
    context = {}

    if request.method == "POST":
        form = ThinkerEmailForm(request.POST)
        # SI pas valide je vais au formulaire avant le return puis return
        if form.is_valid():
            if form.cleaned_data["email"] != user.email:
                messages.add_message(request, messages.ERROR, "Mauvaise adresse mail actuelle renseignée")
                return redirect("account:change-email")

            user_auth = authenticate(email=form.cleaned_data["email"], password=form.cleaned_data["password"])

            if user_auth:
                for other_user in all_users:
                    if form.cleaned_data["new_email"] == other_user.email:
                        messages.add_message(request, messages.ERROR, "Email déjà utilisé")
                        return redirect("account:change-email")

                user.email = form.cleaned_data["new_email"]
                user.save()
                return redirect("account:change-email")

            else:
                messages.add_message(request, messages.ERROR, "Mot de passe invalide")
                return redirect("account:change-email")

    context["form"] = ThinkerEmailForm(initial={"email": user.email})

    return render(request, "accounts/change-email.html", context=context)


class ThinkerPasswordChange(PasswordChangeView):
    template_name = "accounts/change-password.html"
    success_url = reverse_lazy('index')


class ThinkerPasswordReset(PasswordResetView):
    email_template_name = "accounts/reset-password-email.html"
    template_name = "accounts/reset-password.html"
    success_url = reverse_lazy("account:reset-done")


class ThinkerPasswordResetDone(PasswordResetDoneView):
    template_name = "accounts/reset-password-done.html"


class ThinkerPasswordResetConfirm(PasswordResetConfirmView):
    template_name = "accounts/reset-password-confirm.html"
    success_url = reverse_lazy("account:reset-complete")


class ThinkerPasswordResetComplete(PasswordResetCompleteView):
    template_name = "accounts/reset-password-complete.html"

src/accounts/templates/accounts/change-email.html
{% extends 'base.html' %}

{% block head %}
<title>Modifier son email</title>
{% endblock %}

{% block body %}
<div class="container" style="margin-bottom: 15px;">
{% if messages %}
{% for message in messages %}
	<h5 style="color: Red;">{{ message }}</h5>
{% endfor %}
{% endif %}
</div>
<div class="container">
    <div class="row">
        <div class="col">
<form method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}


    <input class="btn btn-outline-primary" type="submit" value="Modifier">
</form>

        </div>
    </div>
</div>
{% endblock %}

src/accounts/templates/accounts/change-password.html
{% extends 'base.html' %}

{% block head %}
<title>Modifier son mot de passe</title>
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col">
<form method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}


    <input class="btn btn-outline-primary" type="submit" value="Modifier">
</form>

        </div>
    </div>
</div>
{% endblock %}

src/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block head %}
<title>Connexion</title>
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col">

<form method="post" class="form">
    {% csrf_token %}
<label for="email">Email</label>
  <input name="email" id="email" type="email">

<label for="password">Mot de passe</label>
  <input type="password" name="password" id="password">

<input type="submit" value="Connexion" class="btn btn-outline-dark">
</form>
                </div>
    </div>

<h3>{{ error }}</h3>
<a href="{% url 'account:reset-password' %}" class="btn btn-outline-dark" style="margin-top: 10px;">Demander un nouveau mot de passe</a>
    </div>
{% endblock %}

src/accounts/templates/accounts/profil.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col">

<form method="post" class="form">
{% csrf_token %}
    {{ form.as_p }}

<input type="submit" value="Modifier" class="btn btn-outline-dark">
</form>
                </div>
    </div>


<a href="{% url 'account:change-password' %}" class="btn btn-outline-dark" style="margin-top: 10px;">Modifier son mot de passe</a>
    <a href="{% url 'account:change-email' %}" class="btn btn-outline-dark" style="margin-top: 10px;">Modifier son adresse Mail</a>
{{ error }}
    </div>
{% endblock %}

src/accounts/templates/accounts/reset-password-complete.html
{% extends 'base.html' %}
{% load i18n static %}

{% block head %}
<title>Nouveau mot de passe créé</title>
{% endblock %}

{% block body %}

<div class="breadcrumbs">
<a href="{% url 'index' %}">{% translate 'Home' %}</a>
&rsaquo; {% translate 'Password reset' %}
</div>




<p>{% translate "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{{ login_url }}">{% translate 'Log in' %}</a></p>

{% endblock %}

src/accounts/templates/accounts/reset-password-confirm.html
{% extends 'base.html' %}
{% load i18n static %}

{% block head %}
<title>Nouveau mot de passe</title>
{% endblock %}

{% block body %}
<div class="breadcrumbs">
<a href="{% url 'index' %}">{% translate 'Home' %}</a>
&rsaquo; {% translate 'Password reset confirmation' %}
</div>

{% if validlink %}

<p>{% translate "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

<form method="post">{% csrf_token %}
<fieldset class="module aligned">
    <input class="hidden" autocomplete="username" value="{{ form.user.get_username }}">
    <div class="form-row field-password1">
        {{ form.new_password1.errors }}
        <label for="id_new_password1">{% translate 'New password:' %}</label>
        {{ form.new_password1 }}
    </div>
    <div class="form-row field-password2">
        {{ form.new_password2.errors }}
        <label for="id_new_password2">{% translate 'Confirm password:' %}</label>
        {{ form.new_password2 }}
    </div>
    <input type="submit" value="{% translate 'Change my password' %}" class="btn btn-outline-dark">
</fieldset>
</form>

{% else %}

<p>{% translate "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}
{% endblock %}

src/accounts/templates/accounts/reset-password-done.html
{% extends 'base.html' %}
{% load i18n %}
{% block head %}
<title>Mail envoyé</title>
{% endblock %}

{% block body %}

<div class="breadcrumbs">
<a href="{% url 'index' %}" class="btn btn-outline-dark">{% translate 'Home' %}</a>
&rsaquo; {% translate 'Password reset' %}
</div>




<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>



{% endblock %}

src/accounts/templates/accounts/reset-password-email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'account:reset-confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

src/accounts/templates/accounts/reset-password.html
{% extends 'base.html' %}

{% block head %}
<title>Récupérer un mot de passe</title>
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col">
<form method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}


    <input class="btn btn-outline-dark" type="submit" value="Récupérer un mot de passe">
</form>

        </div>
    </div>
</div>
{% endblock %}

src/accounts/templates/accounts/signup-valid.html
{% extends 'base.html' %}

{% block head %}
<title>Confirmation d'inscription</title>
{% endblock %}

{% block body %}
<h3>Pour activer votre compte merci de cliquer sur le lien d'activation reçu par email (il met environ 4 min à arriver, pensez à vérifier dans vos spams).</h3>
{% endblock %}

src/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block head %}
<title>Inscription</title>
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col">

<form method="post" class="form">
{% csrf_token %}
    {{ form.as_p }}

<input type="submit" value="S'inscrire" class="btn btn-outline-dark">
</form>
                </div>
    </div>
</div>
{% endblock %}

src/accounts/templates/accounts/signup_valid.html
{% extends 'base.html' %}

{% block head %}
<title>Confirmation d'inscription</title>
{% endblock %}

{% block body %}
<h1>Pour activer votre compte merci de cliquer sur le lien d'activation reçu par email.</h1>

{% endblock %}